name: "Stale File"
description: "Stale File"
author: "kijimaD"
inputs:
  github_token:
    description: 'GitHub token(write + read)'
    required: true
  paths:
    description: 'Paths to be checked'
    required: false
    default: './'
  ignores:
    description: 'Paths to be ignored'
    required: false
    default: ''
  daysUntilStale:
    description: 'stale day'
    required: false
    default: 30
  label:
    description: 'StaleFile issue label'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
      with:
        ruby-version: 3.1

    - name: check stale file
      id: check
      shell: bash
      run: |
        RESULT=$(ruby ./src/main.rb)
        RESULT="${RESULT//$'\n'/'%0A'}" # https://github.community/t/set-output-truncates-multiline-strings/16852
        echo "::set-output name=stdout::$RESULT"

    - name: Set current datetime as env variable
      id: today
      shell: bash
      run: |
        DATE=$(date +'%Y-%m-%d')
        echo "::set-output name=stdout::$DATE"

    - name: Create an issue
      uses: actions-ecosystem/action-create-issue@v1
      with:
        github_token: ${{ inputs.GITHUB_TOKEN }}
        title: 🏜StaleFile | ${{ steps.today.outputs.stdout }}
        body: ${{ steps.check.outputs.stdout }}
        labels: ${{ inputs.label }}

branding:
  icon: "chevron-up"
  color: "green"
