name: "Stale File"
description: "Stale File"
author: "kijimaD"
inputs:
  paths:
    description: 'Paths to be checked'
    required: false
    default: ['./']
  ignores:
    description: 'Paths to be ignored'
    required: false
    default: ['']
  daysUntilStale:
    description: 'stale day'
    required: false
    default: 30
runs:
  # staleファイルを検索+結果を整形してoutput
    steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 3.1
    - name: Run script
      run: |
        ruby src/main.rb

  # issue作成

  # コメント作成

branding:
  icon: "chevron-up"
  color: "green"
