name: Test

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      label:
        required: false
      file_extension:
        required: false
      include:
        required: false
      exclude:
        required: false
      days_until_stale:
        required: false
      header_comment:
        required: false

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          label: StaleFile
          file_extension: '*.md'
          days_until_stale: ${{ github.event.inputs.days_until_stale || 30 }}

  test-passing:
    needs: [ test ]
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - run: echo "All tests have passed."
