name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  test-passing:
    needs: [ test ]
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - run: echo "All tests have passed."
